site_name: Guide utilisateur de Kalechap
theme:
  name: material
  language: fr
  favicon: assets/favicon.svg
  palette:
    # Light Mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: orange
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre

    # Dark Mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: orange
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

extra_css:
  - stylesheets/extra.css

nav:
  - Premiers pas:
      - Accueil: index.md
      - Inscription: inscription.md
      - Connexion: connexion.md
      - Subscription: subscription.md
      - Profil: profil.md
  - Utilisation:
      - Rechercher un service: rechercher-service.md
      - Demander un service: service-request.md
      - Ajouter une offre de service: ajouter-offre.md
      - Code de parrainage: code-parrainage.md
  - Avanc√©:
      - Nombre d'offres de service: nombre-offres-service.md
      - Ajouter une image d'offre: ajouter-image-offre-service.md
      - Ajouter une photo de profil: add-profile-picture.md
